apiVersion: v2
description: Hyperledger Fabric Orderer chart
name: helm-hlf-ord
version: 1.1.0
appVersion: 1.4.3
keywords:
  - blockchain
  - hyperledger
  - fabric
home: http://hyperledger-fabric.readthedocs.io
sources:
  - https://github.com/its-software-services-devops/helm-hlf-ord
icon: https://www.hyperledger.org/wp-content/uploads/2018/04/fabric-logo.png
